name: 'version'
description:
  'Deterministic version similar to git-describe on sparse checkouts.'
author: 'Nicolas Trüssel'

# Define your inputs here.
inputs:
  token:
    description: >
      Access token for the GitHub API. Required to fetch the tags and commits in
      order to calculate the version number
    required: true
    default: ${{ github.token }}

# Define your outputs here.
outputs:
  version:
    description: >
      Version determined by this action

runs:
  using: node20
  main: dist/index.js
